### ISSUE TITLE
Data services Jumpstart (Postgres) fails for microk8s

### ISSUE THREAD

**Issue by bamajeed** [microsoft/azure_arc#1456]
**Jumpstart scenario or ArcBox flavor which you are working on.**
(https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_data/microk8s/azure/arm_template/postgresql/)

**Describe the bug.**
Installation does not complete - with the Windows client unable to connect to the cluster 

**To Reproduce.**
1. follow the jump start instructions. the first part works fine and then I log into the client window machine
2. when logging into the windows client machine the following error is encountered after some time:
3. 
![image](https://user-images.githubusercontent.com/38979131/195830676-272e8cba-9297-494b-b7d2-8348d1fe01e1.png)
with a loop on the powershell terminal stating: No resources found in arc namespace. Waiting for bootstrapper pod.

**Expected behavior.**
Installation on microk8s should work (other scenarios complete successfully e.g. kubeadm)

**Environment summary.**
All according to jumpstart guidance

**Screenshots.**
![image](https://user-images.githubusercontent.com/38979131/195831684-45314bb3-2990-484a-ab09-f187674ce3ab.png)
![image](https://user-images.githubusercontent.com/38979131/195831788-bf1af077-eb15-4a90-b825-6746f3577108.png)

**Additional context.**

**Comment by pabloameijeirascanay** [comment]
Hi @bamajeed, today all is working:
![microk8s](https://user-images.githubusercontent.com/87183849/199722418-5877e0cc-54cf-4c6b-a67b-864a919b08e4.png)
Yesterday's error was related to this KV issue:
![kv](https://user-images.githubusercontent.com/87183849/199722672-5551578f-3b11-4c3e-8c8a-b24b09e1ebd2.png)
This KV issue is now solved.

**Comment by likamrat** [comment]
@bamajeed we are working on doing some refactoring and code optimizations for this scenario. Stay tuned...

**Comment by basimolimajeed** [comment]
I have tried the deployment of data services with microk8s but still getting errors.
![Screenshot 2022-12-20 102507](https://user-images.githubusercontent.com/16608331/208644839-da6b9a92-6ac9-4ac3-9778-3c800632fdbd.jpg)

When I deploy other data controller with Postgresql scenarios (e.g. kubeadm) then it works fine

**Comment by pabloameijeirascanay** [comment]
Hi @basimolimajeed 
I had set [Microk8s version](https://github.com/microsoft/azure_arc/blob/63bf3324e5e37b70f280f04d60472c24e68d58cf/azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/install_microk8s.sh#L47) as 1.2.4 instead of 1.24, I have created a [pull request](https://github.com/microsoft/azure_arc/pull/1584) to update it to 1.25.
Once the pull request is approved everything should work, if you don't want to wait for the approval you can change it in your local and run the following commands in the *azure_arc/azure_arc_data_jumpstart/microk8s/azure/arm_template* directory :
```bash
az group create --name Arc-Data-Microk8s --location "East US"
az deployment group create \
--resource-group Arc-Data-Microk8s \
--name arcdatademo \
--template-file azuredeploy.json \
--parameters customLocationRPOID="$customLocationRPOID" \
--parameters azuredeploy.parameters.json
```
Thanks for reporting the issue.

**Comment by pabloameijeirascanay** [comment]
Hi @basimolimajeed, the [pull request](https://github.com/microsoft/azure_arc/pull/1584) has been approved.

**Comment by basimolimajeed** [comment]
Hi Pablo, this works fine now thank you
